// <auto-generated />
namespace SfoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_username_and_password_to_Ansatt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_username_and_password_to_Ansatt));
        
        string IMigrationMetadata.Id
        {
            get { return "201811131236321_added_username_and_password_to_Ansatt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
