// <auto-generated />
namespace SfoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class populate_SjekkInnLogg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populate_SjekkInnLogg));
        
        string IMigrationMetadata.Id
        {
            get { return "201812101836504_populate_SjekkInnLogg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
