// <auto-generated />
namespace SfoApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pop_ansatte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pop_ansatte));
        
        string IMigrationMetadata.Id
        {
            get { return "201901071722216_pop_ansatte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
